apiVersion: v1
kind: Pod
metadata:
  name: borde-interno
  namespace: reggaeton
spec:
  containers:
    - name: bad-bunny
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano