apiVersion: v1
kind: Pod
metadata:
  name: borde-interno
  namespace: reggaeton
  annotations:
    estudiante: "Ricardo Erazo"
    musica-preferida: "Reggaeton"
spec:
  containers:
    - name: wisin-yandel
      image: nginx

  tolerations:
    - key: "music"
      operator: "Equal"
      value: "perreo-intenso"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - urbano