apiVersion: v1
kind: Pod
metadata:
  name: johan-acosta-rock
  namespace: rock
spec:
  containers:
    - name: soda-stereo
      image: nginx
  tolerations:
    - key: "music"
      operator: "Equal"
      value: "guitarra-electrica"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - metalero
