apiVersion: v1
kind: Pod
metadata:
  name: sin-ganas
  namespace: techno
  annotations:
    estudiante: "Kevin Giron"
    musica-preferida: "rap"
spec:
  containers:
    - name: con-ganas
      image: nginx

  tolerations:
    - key: "music"
      operator: "Equal"
      value: "bass-boost"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: style
                operator: In
                values:
                  - electronico